services:
  keycloak_db:
    image: postgres:14
    environment:
      POSTGRES_DB: keycloak_db
      POSTGRES_USER: keycloak_user
      POSTGRES_PASSWORD: keycloak_password
    volumes:
      - ./postgres-keycloak-data:/var/lib/postgresql/data
    ports:
      - "5433:5432"
  keycloak:
    image: quay.io/keycloak/keycloak:26.6.3
    environment:
      KC_BOOTSTRAP_ADMIN_USERNAME: admin
      KC_BOOTSTRAP_ADMIN_PASSWORD: admin

      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://keycloak_db:5432/keycloak_db
      KC_DB_USERNAME: keycloak_user
      KC_DB_PASSWORD: keycloak_password

      KEYCLOAK_CLIENT_SECRET: ${KEYCLOAK_CLIENT_SECRET}
      YANDEX_CLIENT_ID: ${YANDEX_CLIENT_ID}
      YANDEX_CLIENT_SECRET: ${YANDEX_CLIENT_SECRET}
      LDAP_BIND_CREDENTIAL: ${LDAP_BIND_CREDENTIAL}

    command:
      - start-dev
      - --import-realm

    volumes:
      - ./keycloak/reports-realm-realm.json:/opt/keycloak/data/import/reports-realm-realm.json:ro

    ports:
      - "8080:8080"

    depends_on:
      - keycloak_db
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
  auth_db:
    image: postgres:14-alpine
    environment:
      POSTGRES_DB: bionicpro_auth
      POSTGRES_USER: bionicpro_auth
      POSTGRES_PASSWORD: bionicpro_auth_password
    ports:
      - "5434:5432"
    volumes:
      - auth-db-data:/var/lib/postgresql/data
    healthcheck:
      test:
        - CMD-SHELL
        - pg_isready -U bionicpro_auth -d bionicpro_auth
      interval: 5s
      timeout: 5s
      retries: 10
  openldap:
    image: osixia/openldap:1.5.0
    command:
      - --copy-service
    environment:
      LDAP_ORGANISATION: BionicPRO
      LDAP_DOMAIN: example.com
      LDAP_ADMIN_PASSWORD: admin
      LDAP_CONFIG_PASSWORD: config
      LDAP_TLS: "false"
    ports:
      - "389:389"
    volumes:
      - ./ldap/config.ldif:/container/service/slapd/assets/config/bootstrap/ldif/custom/50-bionicpro.ldif:ro
      - ./ldap-data:/var/lib/ldap
      - ./ldap-config:/etc/ldap/slapd.d
  redis:
    image: redis:7-alpine
    command:
      - redis-server
      - --appendonly
      - "yes"
      - --requirepass
      - bionicpro_redis_password
    ports:
      - "6379:6379"
    volumes:
      - ./redis-data:/data
    healthcheck:
      test:
        - CMD
        - redis-cli
        - -a
        - bionicpro_redis_password
        - ping
      interval: 5s
      timeout: 3s
      retries: 10

volumes:
  auth-db-data:
